version: "3.8"

services:
  mysql:
    image: mysql:8.0.33
    container_name: todo-app-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: todo_app
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo_app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: todo-app-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - todo_app_network

volumes:
  mysql_data:

networks:
  todo_app_network:
    driver: bridge
